# Generated by Django 5.2.6 on 2025-10-06 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_host_vcenter_server'),
        ('playbooks', '0002_playbook_os_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.CharField(max_length=255)),
                ('vcenter_snapshot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('size_mb', models.IntegerField(default=0, help_text='Snapshot size in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_hours', models.IntegerField(default=24, help_text='Hours to keep snapshot before auto-deletion')),
                ('expires_at', models.DateTimeField(help_text='When snapshot will be auto-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='inventory.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.host')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playbooks.playbook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot History',
                'verbose_name_plural': 'Snapshot Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='snapshots_s_created_89fda0_idx'), models.Index(fields=['status'], name='snapshots_s_status_ff2f14_idx'), models.Index(fields=['host'], name='snapshots_s_host_id_588ede_idx'), models.Index(fields=['expires_at'], name='snapshots_s_expires_951a70_idx')],
            },
        ),
    ]
