# Generated by Django 5.2.6 on 2025-10-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshothistory',
            name='script_name',
            field=models.CharField(blank=True, help_text='Name of script if executed via script', max_length=255, null=True),
        ),
    ]
