# Generated by Django 5.2.6 on 2025-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Script name (without extension)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what the script does')),
                ('target_type', models.CharField(choices=[('host', 'Host'), ('group', 'Group')], help_text='Execute on single host or group', max_length=10)),
                ('os_family', models.CharField(choices=[('redhat', 'RedHat/CentOS/Oracle Linux'), ('debian', 'Debian/Ubuntu'), ('windows', 'Windows')], help_text='Operating system family', max_length=20)),
                ('file_path', models.CharField(help_text='Path to script file', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['os_family', 'target_type', 'name'],
                'unique_together': {('name', 'target_type', 'os_family')},
            },
        ),
    ]
