# Generated by Django 5.2.6 on 2025-09-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcentercredential',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vcentercredential',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='vcentercredential',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='vcentercredential',
            name='ssl_verify',
            field=models.BooleanField(blank=True, default=False, help_text='Check to verify SSL certificate', null=True, verbose_name='SSL Verify'),
        ),
        migrations.AlterField(
            model_name='vcentercredential',
            name='user',
            field=models.CharField(max_length=100, verbose_name='User'),
        ),
    ]
