# Generated by Django 5.2.6 on 2025-09-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_vcentercredential_description_and_more'),
    ]

    operations = [
    ]
