# Generated by Django 5.2.6 on 2025-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_merge_20250930_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentcredential',
            name='ssh_key_file_path',
            field=models.CharField(blank=True, help_text='Ruta del archivo de llave SSH en disco', max_length=500, null=True),
        ),
    ]
