# Generated by Django 5.2.6 on 2025-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_deploymentcredential_ssh_key_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentcredential',
            name='ssh_key_file',
            field=models.FileField(blank=True, help_text='Sube el archivo de llave SSH (.pem, .key)', null=True, upload_to='ssh/'),
        ),
        migrations.AlterField(
            model_name='deploymentcredential',
            name='ssh_private_key',
            field=models.TextField(blank=True, help_text='Pega la llave privada SSH (opcional si subes archivo)', null=True),
        ),
    ]
