# Generated by Django 5.2.6 on 2025-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_deploymentcredential_ssh_key_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('host', 'Host'), ('group', 'Group')], default='host', max_length=10)),
                ('file', models.FileField(upload_to='j2/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ansible Template',
                'verbose_name_plural': 'Ansible Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
