# Generated by Django 5.2.6 on 2025-10-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_ansibletemplate'),
    ]

    operations = [
    ]
