# Generated by Django 5.2.6 on 2025-10-02 16:59

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20251002_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcentercredential',
            name='name',
            field=models.CharField(default='vCenter', help_text='Friendly name to identify this vCenter', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ansibletemplate',
            name='file',
            field=models.FileField(upload_to=settings.models.ansible_template_upload_path),
        ),
    ]
