# Generated by Django 5.2.6 on 2025-10-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_vcentercredential_name_alter_ansibletemplate_file'),
    ]

    operations = [
    ]
