# Generated by Django 5.2.6 on 2025-10-02 20:35

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20251002_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcertificate',
            options={'ordering': ['name'], 'verbose_name': 'SSL Certificate', 'verbose_name_plural': 'SSL Certificates'},
        ),
        migrations.RemoveField(
            model_name='sslcertificate',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='sslcertificate',
            name='file',
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='cert_file',
            field=models.FileField(blank=True, help_text='Certificate file (.crt)', null=True, upload_to=settings.models.ssl_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='key_file',
            field=models.FileField(blank=True, help_text='Private key file (.key)', null=True, upload_to=settings.models.ssl_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='provider_file',
            field=models.FileField(blank=True, help_text='Provider/CA bundle file (.crt)', null=True, upload_to=settings.models.ssl_certificate_upload_path),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='name',
            field=models.CharField(help_text='Certificate name (e.g., example.com)', max_length=100, unique=True),
        ),
    ]
