# Generated by Django 5.2.6 on 2025-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_sslcertificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name to identify these credentials', max_length=200, verbose_name='Name')),
                ('username', models.CharField(help_text='Windows username (e.g., Administrator)', max_length=200, verbose_name='Username')),
                ('password', models.CharField(help_text='Windows password', max_length=500, verbose_name='Password')),
                ('domain', models.CharField(blank=True, help_text='Active Directory domain (optional)', max_length=200, verbose_name='Domain')),
                ('auth_type', models.CharField(choices=[('ntlm', 'NTLM'), ('basic', 'Basic'), ('credssp', 'CredSSP'), ('kerberos', 'Kerberos')], default='ntlm', help_text='WinRM authentication method', max_length=20, verbose_name='Authentication Type')),
                ('use_https', models.BooleanField(default=False, help_text='Use HTTPS (port 5986) instead of HTTP (port 5985)', verbose_name='Use HTTPS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Windows Credential',
                'verbose_name_plural': 'Windows Credentials',
                'ordering': ['name'],
            },
        ),
    ]
