# Generated by Django 5.2.6 on 2025-10-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_windowscredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentcredential',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vcentercredential',
            name='password',
            field=models.TextField(verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='windowscredential',
            name='password',
            field=models.TextField(help_text='Windows password (encrypted)', verbose_name='Password'),
        ),
    ]
