# Generated by Django 5.2.6 on 2025-09-25 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='inventory.environment', verbose_name='Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('operating_system', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('other', 'Other')], default='linux', max_length=30, verbose_name='Operating System')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='inventory.environment', verbose_name='Environment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='inventory.group', verbose_name='Group')),
            ],
        ),
    ]
