# Generated by Django 5.2.6 on 2025-09-25 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('settings', '0002_alter_vcentercredential_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ansible_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ansible Password'),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ansible Port'),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_python_interpreter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ansible Python Interpreter'),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_ssh_common_args',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ansible SSH Common Args'),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_ssh_private_key_file',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ansible SSH Private Key File'),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ansible User'),
        ),
        migrations.AddField(
            model_name='host',
            name='deployment_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.deploymentcredential', verbose_name='Deployment Credential'),
        ),
        migrations.AddField(
            model_name='host',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tags'),
        ),
    ]
