# Generated by Django 5.2.6 on 2025-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_host_ansible_password_host_ansible_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=models.CharField(choices=[('redhat', 'Redhat'), ('debian', 'Debian')], default='linux', max_length=30, verbose_name='Operating System'),
        ),
    ]
