# Generated by Django 5.2.6 on 2025-09-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_host_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
