# Generated by Django 5.2.6 on 2025-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='vcenter_server',
            field=models.CharField(blank=True, help_text='vCenter server managing this VM', max_length=200, verbose_name='vCenter Server'),
        ),
    ]
