# Generated by Django 5.2.6 on 2025-10-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_host_vcenter_server'),
        ('settings', '0011_windowscredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='windows_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.windowscredential', verbose_name='Windows Credential'),
        ),
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=models.CharField(choices=[('redhat', 'Redhat'), ('debian', 'Debian'), ('windows', 'Windows')], default='linux', max_length=30, verbose_name='Operating System'),
        ),
    ]
