# Generated by Django 5.2.6 on 2025-10-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_host_windows_credential_alter_host_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='windows_password',
            field=models.CharField(blank=True, help_text='WinRM password for Windows hosts', max_length=200, verbose_name='Windows Password'),
        ),
        migrations.AddField(
            model_name='host',
            name='windows_user',
            field=models.CharField(blank=True, help_text='WinRM username for Windows hosts', max_length=100, verbose_name='Windows User'),
        ),
    ]
