# Generated by Django 5.2.6 on 2025-09-30 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=200)),
                ('target_type', models.CharField(default='VM', max_length=50)),
                ('playbook', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='running', max_length=20)),
                ('ansible_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datacenter', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deployment History',
                'verbose_name_plural': 'Deployment Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
