# Generated by Django 5.2.6 on 2025-10-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthistory',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
