# Generated by Django 5.2.6 on 2025-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_deploymenthistory_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthistory',
            name='snapshot_name',
            field=models.CharField(blank=True, help_text='Nombre del snapshot creado antes de ejecutar el playbook', max_length=255, null=True),
        ),
    ]
