# Generated by Django 5.2.6 on 2025-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_deploymenthistory_snapshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenthistory',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea Celery para tareas asíncronas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deploymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
