# Generated by Django 5.2.6 on 2025-10-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('playbook_type', models.CharField(choices=[('host', 'Host'), ('group', 'Group')], default='host', max_length=10)),
                ('file', models.FileField(upload_to='playbooks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['playbook_type', 'name'],
            },
        ),
    ]
