# Generated by Django 4.2.24 on 2025-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='os_family',
            field=models.CharField(choices=[('redhat', 'RedHat/CentOS'), ('debian', 'Debian/Ubuntu')], default='redhat', max_length=10),
        ),
    ]
