# Generated by Django 5.2.6 on 2025-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0002_playbook_os_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='os_family',
            field=models.CharField(choices=[('redhat', 'RedHat/CentOS'), ('debian', 'Debian/Ubuntu'), ('windows', 'Windows')], default='redhat', max_length=10),
        ),
    ]
