# Generated by Django 5.2.6 on 2025-10-24 02:43

import playbooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0003_alter_playbook_os_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='file',
            field=models.FileField(upload_to=playbooks.models.playbook_upload_path),
        ),
    ]
