"""
Django settings for diaken project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: Keep the secret key used in production secret!
# For production, override this via DJANGO_SECRET_KEY environment variable
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-key-change-in-production-8k#2m@9x!p$v7n&q3w5e'
)

# SECURITY WARNING: Don't run with debug turned on in production!
# For production, set DJANGO_DEBUG=False in environment or .env file
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS configuration
# For production, set DJANGO_ALLOWED_HOSTS in environment or .env file
ALLOWED_HOSTS_STR = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_STR.split(',') if h.strip()]
else:
    # Default: Allow all hosts in development, restrict in production
    ALLOWED_HOSTS = ['*'] if DEBUG else []

# CSRF Trusted Origins
# For production, set DJANGO_CSRF_TRUSTED_ORIGINS in environment or .env file
CSRF_TRUSTED_ORIGINS_STR = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if CSRF_TRUSTED_ORIGINS_STR:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in CSRF_TRUSTED_ORIGINS_STR.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [    
    'deploy',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'settings',
    'inventory',
    'history',
    'playbooks',
    'scheduler',
    'users',
    'dashboard',
    'snapshots',
    'scripts',
    'notifications',
    'addressing',
]

LOGIN_URL = '/login/'

STATIC_URL = '/static/'
# La asignación de DIRS se mueve abajo, después de definir TEMPLATES


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'diaken.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

WSGI_APPLICATION = 'diaken.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration
# Use environment variables for database configuration
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'unix_socket': os.environ.get('DB_SOCKET', ''),
        } if os.environ.get('DB_ENGINE') == 'django.db.backends.mysql' else {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/' # Duplicated, using line 50

# Media files (User uploaded files)
MEDIA_URL = '/media/'
# Use absolute path for MEDIA_ROOT to ensure portability
MEDIA_ROOT = os.path.join(str(BASE_DIR), 'media')

# Structure within MEDIA_ROOT:
# media/
#   playbooks/
#     {os_family}/    # windows, redhat, debian
#       {target_type}/ # host, group
#   scripts/
#     {os_family}/    # powershell, redhat, debian
#       {target_type}/ # host, group

# Ansible configuration
ANSIBLE_PLAYBOOK_PATH = str(BASE_DIR / 'venv' / 'bin' / 'ansible-playbook')

# Celery Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Bogota'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files configuration
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files collection directory
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================================
# WINDOWS UPDATE PLAYBOOK CONFIGURATION
# ============================================================================
# Windows Update settings are now managed via GlobalSetting model in the database
# See: settings app -> Global Settings in admin panel
# Keys:
#   - windows_update_max_cycles (default: 5)
#   - windows_update_install_timeout (default: 5400)
#   - windows_update_reboot_timeout (default: 600)
#   - windows_update_post_reboot_delay (default: 30)
#   - windows_update_wsus_sync_wait (default: 30)

# ============================================================================
# CREDENTIAL ENCRYPTION CONFIGURATION
# ============================================================================
# Encryption key for storing sensitive credentials (vCenter, etc.)
# Auto-generated if not provided via environment variable
import secrets

# Try to get from environment, otherwise generate a default key
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')

if not ENCRYPTION_KEY:
    # Path to store the encryption key
    KEY_FILE = os.path.join(BASE_DIR, '.encryption_key')
    
    # Try to load existing key from file
    if os.path.exists(KEY_FILE):
        try:
            with open(KEY_FILE, 'r') as f:
                ENCRYPTION_KEY = f.read().strip()
        except Exception:
            pass
    
    # Generate new key if still not available
    if not ENCRYPTION_KEY:
        # Generate a secure random key (32 bytes = 256 bits)
        ENCRYPTION_KEY = secrets.token_urlsafe(32)
        
        # Save it for future use
        try:
            with open(KEY_FILE, 'w') as f:
                f.write(ENCRYPTION_KEY)
            # Set restrictive permissions (only owner can read/write)
            os.chmod(KEY_FILE, 0o600)
        except Exception as e:
            # If we can't save it, at least log a warning
            import sys
            print(f"Warning: Could not save encryption key to file: {e}", file=sys.stderr)

# Export to environment for child processes
os.environ['ENCRYPTION_KEY'] = ENCRYPTION_KEY

# ============================================================
# NGINX REVERSE PROXY CONFIGURATION
# ============================================================
# Django needs to trust the proxy headers sent by nginx

# Trust proxy headers
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security settings for HTTPS
if not DEBUG:
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
# Allowed hosts should include your domain
# Example: ALLOWED_HOSTS = ['diaken.example.com', '192.168.1.100']

# CSRF trusted origins should include https://
# Example: CSRF_TRUSTED_ORIGINS = ['https://diaken.example.com', 'https://192.168.1.100']
