# Generated by Django 5.2.6 on 2025-10-14 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftTeamsWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this webhook (e.g., 'DevOps Team', 'Production Alerts')", max_length=255, unique=True)),
                ('webhook_url', models.URLField(help_text='Microsoft Teams Incoming Webhook URL', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('active', models.BooleanField(default=True, help_text='Enable/disable this webhook')),
                ('notify_deployments', models.BooleanField(default=True, help_text='Send notifications for VM deployments')),
                ('notify_playbook_executions', models.BooleanField(default=True, help_text='Send notifications for playbook executions')),
                ('notify_scheduled_tasks', models.BooleanField(default=True, help_text='Send notifications for scheduled task executions')),
                ('notify_failures_only', models.BooleanField(default=False, help_text='Only send notifications for failed executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Microsoft Teams Webhook',
                'verbose_name_plural': 'Microsoft Teams Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deployment', 'VM Deployment'), ('playbook', 'Playbook Execution'), ('scheduled_task', 'Scheduled Task')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('response_message', models.TextField(blank=True)),
                ('deployment_id', models.IntegerField(blank=True, null=True)),
                ('scheduled_task_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.microsoftteamswebhook')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
