# Generated by Django 5.2.6 on 2025-10-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftteamswebhook',
            name='notify_linux_deployments',
            field=models.BooleanField(default=True, help_text='Send notifications for Linux VM deployments'),
        ),
        migrations.AddField(
            model_name='microsoftteamswebhook',
            name='notify_linux_playbooks',
            field=models.BooleanField(default=True, help_text='Send notifications for Linux playbook executions'),
        ),
        migrations.AddField(
            model_name='microsoftteamswebhook',
            name='notify_windows_deployments',
            field=models.BooleanField(default=True, help_text='Send notifications for Windows VM deployments'),
        ),
        migrations.AddField(
            model_name='microsoftteamswebhook',
            name='notify_windows_playbooks',
            field=models.BooleanField(default=True, help_text='Send notifications for Windows playbook executions'),
        ),
        migrations.AlterField(
            model_name='microsoftteamswebhook',
            name='notify_failures_only',
            field=models.BooleanField(default=False, help_text='Only send notifications for failed executions (applies to all types)'),
        ),
    ]
