# Generated by Django 5.2.6 on 2025-10-03 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_host_name'),
        ('playbooks', '0002_playbook_os_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('host', 'Execute on Host'), ('group', 'Execute on Group')], max_length=10)),
                ('name', models.CharField(help_text='Task name/description', max_length=200)),
                ('scheduled_datetime', models.DateTimeField(help_text='When to execute this task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('execution_started_at', models.DateTimeField(blank=True, null=True)),
                ('execution_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deployment_history_id', models.IntegerField(blank=True, help_text='ID of DeploymentHistory record', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.environment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.host')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
                'indexes': [models.Index(fields=['status', 'scheduled_datetime'], name='scheduler_s_status_f5d107_idx'), models.Index(fields=['task_type'], name='scheduler_s_task_ty_cf4b38_idx')],
            },
        ),
    ]
