# Generated by Django 5.2.6 on 2025-10-03 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('task_type', models.CharField(max_length=10)),
                ('target_name', models.CharField(help_text='Host or Group name', max_length=200)),
                ('target_ip', models.CharField(blank=True, help_text='IP address(es)', max_length=200)),
                ('playbook_name', models.CharField(max_length=200)),
                ('environment_name', models.CharField(blank=True, max_length=100)),
                ('ansible_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduler.scheduledtask')),
            ],
            options={
                'verbose_name': 'Scheduled Task History',
                'verbose_name_plural': 'Scheduled Task Histories',
                'ordering': ['-executed_at'],
            },
        ),
    ]
