# Generated by Django 5.2.6 on 2025-10-03 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduledtaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtaskhistory',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Original scheduled datetime'),
        ),
    ]
