# Generated by Django 5.2.6 on 2025-10-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduledtaskhistory_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='create_snapshot',
            field=models.BooleanField(default=False, help_text='Create snapshot before execution'),
        ),
    ]
