# Generated by Django 5.2.6 on 2025-10-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduledtask_create_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='scheduled_task_history_id',
            field=models.IntegerField(blank=True, help_text='ID of ScheduledTaskHistory record', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='deployment_history_id',
            field=models.IntegerField(blank=True, help_text='ID of DeploymentHistory record (deprecated, use scheduled_task_history_id)', null=True),
        ),
    ]
