# Generated by Django 5.2.6 on 2025-10-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0003_alter_playbook_os_family'),
        ('scheduler', '0005_scheduledtask_scheduled_task_history_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='execution_type',
            field=models.CharField(default='playbook', help_text='Type of execution: playbook or script', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='os_family',
            field=models.CharField(blank=True, help_text='OS family: redhat, debian, or windows', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='script_id',
            field=models.IntegerField(blank=True, help_text='ID of Script to execute (for script execution)', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbook'),
        ),
    ]
