# Generated by Django 5.2.6 on 2025-10-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_scheduledtask_execution_type_scheduledtask_os_family_and_more'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='script_id',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='script',
            field=models.ForeignKey(blank=True, help_text='Script to execute (for script execution)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scripts.script'),
        ),
    ]
