# Generated by Django 5.2.6 on 2025-11-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_scheduledtask_script_id_scheduledtask_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='snapshot_created',
            field=models.BooleanField(default=False, help_text='Whether snapshot has been created (for scheduled tasks)'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='snapshot_name',
            field=models.CharField(blank=True, help_text='Name of the created snapshot', max_length=500, null=True),
        ),
    ]
